apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  ports:
    - port: 80
      targetPort: frontend-port
      protocol: TCP
    - port: 443
      targetPort: frontend-port
      protocol: TCP
  selector:
    app: frontend
  type: LoadBalancer